services:
  yt-dlp:
    build: ./yt-dlp
    devices:
      - /dev/dri/renderD128
    volumes:
      - media:/downloads
      - yt-dlp-config:/config

volumes:
  # NFS Volumes
  media:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${MEDIA_HOST},rw,hard,nolock,nfsvers=4
      device: ":${MEDIA_HOST_DIR}"

  # Local Volumes
  yt-dlp-config:
